/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as OnboardingIndexRouteImport } from "./routes/onboarding/index"
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index"
import { Route as OnboardingWelcomeRouteImport } from "./routes/onboarding/welcome"
import { Route as OnboardingSetPinRouteImport } from "./routes/onboarding/set-pin"
import { Route as OnboardingCreateSignatureRouteImport } from "./routes/onboarding/create-signature"
import { Route as InviteInviteIdRouteImport } from "./routes/invite/$inviteId"
import { Route as DashboardConnectionsIndexRouteImport } from "./routes/dashboard/connections/index"
import { Route as DashboardSettingsProfileRouteImport } from "./routes/dashboard/settings/profile"
import { Route as DashboardSettingsPermissionsRouteImport } from "./routes/dashboard/settings/permissions"
import { Route as DashboardSignatureCreateIndexRouteImport } from "./routes/dashboard/signature/create/index"
import { Route as DashboardEnvelopeCreateIndexRouteImport } from "./routes/dashboard/envelope/create/index"
import { Route as DashboardDocumentSignIndexRouteImport } from "./routes/dashboard/document/sign/index"
import { Route as DashboardDocumentAllIndexRouteImport } from "./routes/dashboard/document/all/index"
import { Route as DashboardEnvelopeCreateAddSignIndexRouteImport } from "./routes/dashboard/envelope/create/add-sign/index"

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: "/onboarding/",
  path: "/onboarding/",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: "/onboarding/welcome",
  path: "/onboarding/welcome",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSetPinRoute = OnboardingSetPinRouteImport.update({
  id: "/onboarding/set-pin",
  path: "/onboarding/set-pin",
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCreateSignatureRoute =
  OnboardingCreateSignatureRouteImport.update({
    id: "/onboarding/create-signature",
    path: "/onboarding/create-signature",
    getParentRoute: () => rootRouteImport,
  } as any)
const InviteInviteIdRoute = InviteInviteIdRouteImport.update({
  id: "/invite/$inviteId",
  path: "/invite/$inviteId",
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardConnectionsIndexRoute =
  DashboardConnectionsIndexRouteImport.update({
    id: "/connections/",
    path: "/connections/",
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: "/settings/profile",
    path: "/settings/profile",
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsPermissionsRoute =
  DashboardSettingsPermissionsRouteImport.update({
    id: "/settings/permissions",
    path: "/settings/permissions",
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSignatureCreateIndexRoute =
  DashboardSignatureCreateIndexRouteImport.update({
    id: "/signature/create/",
    path: "/signature/create/",
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEnvelopeCreateIndexRoute =
  DashboardEnvelopeCreateIndexRouteImport.update({
    id: "/envelope/create/",
    path: "/envelope/create/",
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDocumentSignIndexRoute =
  DashboardDocumentSignIndexRouteImport.update({
    id: "/document/sign/",
    path: "/document/sign/",
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDocumentAllIndexRoute =
  DashboardDocumentAllIndexRouteImport.update({
    id: "/document/all/",
    path: "/document/all/",
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEnvelopeCreateAddSignIndexRoute =
  DashboardEnvelopeCreateAddSignIndexRouteImport.update({
    id: "/envelope/create/add-sign/",
    path: "/envelope/create/add-sign/",
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardRouteRouteWithChildren
  "/invite/$inviteId": typeof InviteInviteIdRoute
  "/onboarding/create-signature": typeof OnboardingCreateSignatureRoute
  "/onboarding/set-pin": typeof OnboardingSetPinRoute
  "/onboarding/welcome": typeof OnboardingWelcomeRoute
  "/dashboard/": typeof DashboardIndexRoute
  "/onboarding/": typeof OnboardingIndexRoute
  "/dashboard/settings/permissions": typeof DashboardSettingsPermissionsRoute
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute
  "/dashboard/connections/": typeof DashboardConnectionsIndexRoute
  "/dashboard/document/all/": typeof DashboardDocumentAllIndexRoute
  "/dashboard/document/sign/": typeof DashboardDocumentSignIndexRoute
  "/dashboard/envelope/create/": typeof DashboardEnvelopeCreateIndexRoute
  "/dashboard/signature/create/": typeof DashboardSignatureCreateIndexRoute
  "/dashboard/envelope/create/add-sign/": typeof DashboardEnvelopeCreateAddSignIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/invite/$inviteId": typeof InviteInviteIdRoute
  "/onboarding/create-signature": typeof OnboardingCreateSignatureRoute
  "/onboarding/set-pin": typeof OnboardingSetPinRoute
  "/onboarding/welcome": typeof OnboardingWelcomeRoute
  "/dashboard": typeof DashboardIndexRoute
  "/onboarding": typeof OnboardingIndexRoute
  "/dashboard/settings/permissions": typeof DashboardSettingsPermissionsRoute
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute
  "/dashboard/connections": typeof DashboardConnectionsIndexRoute
  "/dashboard/document/all": typeof DashboardDocumentAllIndexRoute
  "/dashboard/document/sign": typeof DashboardDocumentSignIndexRoute
  "/dashboard/envelope/create": typeof DashboardEnvelopeCreateIndexRoute
  "/dashboard/signature/create": typeof DashboardSignatureCreateIndexRoute
  "/dashboard/envelope/create/add-sign": typeof DashboardEnvelopeCreateAddSignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/dashboard": typeof DashboardRouteRouteWithChildren
  "/invite/$inviteId": typeof InviteInviteIdRoute
  "/onboarding/create-signature": typeof OnboardingCreateSignatureRoute
  "/onboarding/set-pin": typeof OnboardingSetPinRoute
  "/onboarding/welcome": typeof OnboardingWelcomeRoute
  "/dashboard/": typeof DashboardIndexRoute
  "/onboarding/": typeof OnboardingIndexRoute
  "/dashboard/settings/permissions": typeof DashboardSettingsPermissionsRoute
  "/dashboard/settings/profile": typeof DashboardSettingsProfileRoute
  "/dashboard/connections/": typeof DashboardConnectionsIndexRoute
  "/dashboard/document/all/": typeof DashboardDocumentAllIndexRoute
  "/dashboard/document/sign/": typeof DashboardDocumentSignIndexRoute
  "/dashboard/envelope/create/": typeof DashboardEnvelopeCreateIndexRoute
  "/dashboard/signature/create/": typeof DashboardSignatureCreateIndexRoute
  "/dashboard/envelope/create/add-sign/": typeof DashboardEnvelopeCreateAddSignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/dashboard"
    | "/invite/$inviteId"
    | "/onboarding/create-signature"
    | "/onboarding/set-pin"
    | "/onboarding/welcome"
    | "/dashboard/"
    | "/onboarding/"
    | "/dashboard/settings/permissions"
    | "/dashboard/settings/profile"
    | "/dashboard/connections/"
    | "/dashboard/document/all/"
    | "/dashboard/document/sign/"
    | "/dashboard/envelope/create/"
    | "/dashboard/signature/create/"
    | "/dashboard/envelope/create/add-sign/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/invite/$inviteId"
    | "/onboarding/create-signature"
    | "/onboarding/set-pin"
    | "/onboarding/welcome"
    | "/dashboard"
    | "/onboarding"
    | "/dashboard/settings/permissions"
    | "/dashboard/settings/profile"
    | "/dashboard/connections"
    | "/dashboard/document/all"
    | "/dashboard/document/sign"
    | "/dashboard/envelope/create"
    | "/dashboard/signature/create"
    | "/dashboard/envelope/create/add-sign"
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/invite/$inviteId"
    | "/onboarding/create-signature"
    | "/onboarding/set-pin"
    | "/onboarding/welcome"
    | "/dashboard/"
    | "/onboarding/"
    | "/dashboard/settings/permissions"
    | "/dashboard/settings/profile"
    | "/dashboard/connections/"
    | "/dashboard/document/all/"
    | "/dashboard/document/sign/"
    | "/dashboard/envelope/create/"
    | "/dashboard/signature/create/"
    | "/dashboard/envelope/create/add-sign/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  InviteInviteIdRoute: typeof InviteInviteIdRoute
  OnboardingCreateSignatureRoute: typeof OnboardingCreateSignatureRoute
  OnboardingSetPinRoute: typeof OnboardingSetPinRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/dashboard": {
      id: "/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding/": {
      id: "/onboarding/"
      path: "/onboarding"
      fullPath: "/onboarding/"
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard/": {
      id: "/dashboard/"
      path: "/"
      fullPath: "/dashboard/"
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/onboarding/welcome": {
      id: "/onboarding/welcome"
      path: "/onboarding/welcome"
      fullPath: "/onboarding/welcome"
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding/set-pin": {
      id: "/onboarding/set-pin"
      path: "/onboarding/set-pin"
      fullPath: "/onboarding/set-pin"
      preLoaderRoute: typeof OnboardingSetPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/onboarding/create-signature": {
      id: "/onboarding/create-signature"
      path: "/onboarding/create-signature"
      fullPath: "/onboarding/create-signature"
      preLoaderRoute: typeof OnboardingCreateSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invite/$inviteId": {
      id: "/invite/$inviteId"
      path: "/invite/$inviteId"
      fullPath: "/invite/$inviteId"
      preLoaderRoute: typeof InviteInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/dashboard/connections/": {
      id: "/dashboard/connections/"
      path: "/connections"
      fullPath: "/dashboard/connections/"
      preLoaderRoute: typeof DashboardConnectionsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/settings/profile": {
      id: "/dashboard/settings/profile"
      path: "/settings/profile"
      fullPath: "/dashboard/settings/profile"
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/settings/permissions": {
      id: "/dashboard/settings/permissions"
      path: "/settings/permissions"
      fullPath: "/dashboard/settings/permissions"
      preLoaderRoute: typeof DashboardSettingsPermissionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/signature/create/": {
      id: "/dashboard/signature/create/"
      path: "/signature/create"
      fullPath: "/dashboard/signature/create/"
      preLoaderRoute: typeof DashboardSignatureCreateIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/envelope/create/": {
      id: "/dashboard/envelope/create/"
      path: "/envelope/create"
      fullPath: "/dashboard/envelope/create/"
      preLoaderRoute: typeof DashboardEnvelopeCreateIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/document/sign/": {
      id: "/dashboard/document/sign/"
      path: "/document/sign"
      fullPath: "/dashboard/document/sign/"
      preLoaderRoute: typeof DashboardDocumentSignIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/document/all/": {
      id: "/dashboard/document/all/"
      path: "/document/all"
      fullPath: "/dashboard/document/all/"
      preLoaderRoute: typeof DashboardDocumentAllIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    "/dashboard/envelope/create/add-sign/": {
      id: "/dashboard/envelope/create/add-sign/"
      path: "/envelope/create/add-sign"
      fullPath: "/dashboard/envelope/create/add-sign/"
      preLoaderRoute: typeof DashboardEnvelopeCreateAddSignIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsPermissionsRoute: typeof DashboardSettingsPermissionsRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardConnectionsIndexRoute: typeof DashboardConnectionsIndexRoute
  DashboardDocumentAllIndexRoute: typeof DashboardDocumentAllIndexRoute
  DashboardDocumentSignIndexRoute: typeof DashboardDocumentSignIndexRoute
  DashboardEnvelopeCreateIndexRoute: typeof DashboardEnvelopeCreateIndexRoute
  DashboardSignatureCreateIndexRoute: typeof DashboardSignatureCreateIndexRoute
  DashboardEnvelopeCreateAddSignIndexRoute: typeof DashboardEnvelopeCreateAddSignIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsPermissionsRoute: DashboardSettingsPermissionsRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardConnectionsIndexRoute: DashboardConnectionsIndexRoute,
  DashboardDocumentAllIndexRoute: DashboardDocumentAllIndexRoute,
  DashboardDocumentSignIndexRoute: DashboardDocumentSignIndexRoute,
  DashboardEnvelopeCreateIndexRoute: DashboardEnvelopeCreateIndexRoute,
  DashboardSignatureCreateIndexRoute: DashboardSignatureCreateIndexRoute,
  DashboardEnvelopeCreateAddSignIndexRoute:
    DashboardEnvelopeCreateAddSignIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  InviteInviteIdRoute: InviteInviteIdRoute,
  OnboardingCreateSignatureRoute: OnboardingCreateSignatureRoute,
  OnboardingSetPinRoute: OnboardingSetPinRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
