import { $ } from "bun";
import hre from "hardhat";
import { getAddress, toHex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import type { ChainKey } from "../definitions/index.js";

const DEFINITIONS_FILE_PREFIX = "export const definitions = ";
const DEFINITIONS_FILE_SUFFIX = " as const;";

const CHAIN_ID = {
	local: 31337,
	testnet: 84532, // Base Sepolia
	mainnet: 8453, // Base
} as const;

/** Hardhat-only: funded on every local deploy for invoice / USDC flow testing. */
const LOCAL_MOCK_USDC_RECIPIENT = getAddress(
	"0x900aEe86E4a368653217D8a952ae0B781980ea4b",
);
/** 10_000_000 USDC (6 decimals). */
const LOCAL_MOCK_USDC_MINT_AMOUNT = 10_000_000n * 10n ** 6n;

function chainName(chainId: number): ChainKey {
	if (chainId === CHAIN_ID.local) return "local";
	if (chainId === CHAIN_ID.testnet) return "testnet";
	if (chainId === CHAIN_ID.mainnet) return "mainnet";
	throw new Error(`Unsupported chainId ${chainId}`);
}

async function main() {
	const chainId = hre.network.config.chainId;
	const deployerPrivateKey = Bun.env.FC_PVT_KEY as `0x${string}` | undefined;

	if (!chainId) {
		console.error(
			"No chainId found in network config, how will we deploy to this network?",
		);
		process.exit(1);
	}

	if (!deployerPrivateKey) {
		console.error("FC_PVT_KEY is required for deployment");
		process.exit(1);
	}

	const deployerAddress = privateKeyToAccount(deployerPrivateKey).address;
	const deployer = await hre.viem.getWalletClient(deployerAddress);

	console.log("Deploying contracts as", {
		address: deployer.account.address,
	});

	const manager = await hre.viem.deployContract("FSManager", [], {
		client: { wallet: deployer },
	});
	console.log("FSManager deployed at:", manager.address);

	// Wait for deployment to be confirmed
	await new Promise((resolve) => setTimeout(resolve, 3000));

	// Verify deployment succeeded by checking code at address
	const publicClient = await hre.viem.getPublicClient();
	const code = await publicClient.getBytecode({ address: manager.address });
	if (!code || code === "0x") {
		console.error("Deployment failed - no code at manager address");
		process.exit(1);
	}

	const fileRegistry = await hre.viem.getContractAt(
		"FSFileRegistry",
		await manager.read.fileRegistry(),
	);
	const keyRegistry = await hre.viem.getContractAt(
		"FSKeyRegistry",
		await manager.read.keyRegistry(),
	);
	const escrow = await hre.viem.getContractAt(
		"FSEscrow",
		await manager.read.escrow(),
	);

	let mockUsdc: undefined | Awaited<ReturnType<typeof hre.viem.deployContract>>;

	if (chainId === CHAIN_ID.local) {
		mockUsdc = await hre.viem.deployContract(
			"MockUSDCToken",
			[deployer.account.address],
			{ client: { wallet: deployer } },
		);
		console.log("MockUSDCToken deployed at:", mockUsdc.address);

		const mintHash = await mockUsdc.write.mint([
			LOCAL_MOCK_USDC_RECIPIENT,
			LOCAL_MOCK_USDC_MINT_AMOUNT,
		]);
		await publicClient.waitForTransactionReceipt({ hash: mintHash });
		console.log("MockUSDC minted to test wallet:", {
			to: LOCAL_MOCK_USDC_RECIPIENT,
			amount: LOCAL_MOCK_USDC_MINT_AMOUNT.toString(),
			txHash: mintHash,
		});

		const mockAddrPath = "definitions/mock-usdc.ts";
		await Bun.write(
			mockAddrPath,
			"/** Auto-generated by scripts/deploy.ts (local Hardhat) — do not edit */\n" +
				`export const LOCAL_MOCK_USDC_ADDRESS = ${JSON.stringify(
					getAddress(mockUsdc.address),
				)} as const;\n`,
		);
		console.log(`Wrote ${mockAddrPath}`);
	}

	console.log("Contracts deployed");

	const definitions = {
		FSManager: {
			address: getAddress(manager.address),
			abi: manager.abi,
		},
		FSFileRegistry: {
			address: getAddress(fileRegistry.address),
			abi: fileRegistry.abi,
		},
		FSKeyRegistry: {
			address: getAddress(keyRegistry.address),
			abi: keyRegistry.abi,
		},
		FSEscrow: {
			address: getAddress(escrow.address),
			abi: escrow.abi,
		},
		...(chainId === CHAIN_ID.local && mockUsdc
			? {
					MockUSDC: {
						address: getAddress(mockUsdc.address),
						abi: mockUsdc.abi,
					},
				}
			: {}),
	} as const;

	const envName = chainName(chainId);
	const singleChainDefinitions = { [toHex(chainId)]: definitions };
	const definitionsPath = `definitions/${envName}.ts`;
	await Bun.write(
		definitionsPath,
		DEFINITIONS_FILE_PREFIX +
			JSON.stringify(singleChainDefinitions, null, 2) +
			DEFINITIONS_FILE_SUFFIX,
	);
	console.log(`Definitions written to ${definitionsPath}`);

	console.log({
		chain: envName,
		chainId,
	});

	const networkName = hre.network.name;
	if (networkName === "baseSepolia" || networkName === "base") {
		try {
			await $`bunx --bun hardhat verify --network ${networkName} ${manager.address} --force`;
			await sleep(1000);
			await $`bunx --bun hardhat verify --network ${networkName} ${fileRegistry.address} --force`;
			await sleep(1000);
			await $`bunx --bun hardhat verify --network ${networkName} ${keyRegistry.address} --force`;
			await sleep(1000);
			await $`bunx --bun hardhat verify --network ${networkName} ${escrow.address} --force`;
		} catch (_) {}
		console.log(`Contracts verified on ${networkName} block explorer`);
	}
}

async function sleep(ms: number) {
	return new Promise((resolve) => setTimeout(resolve, ms));
}

main()
	.then(() => console.log("Deployment script finished"))
	.catch((e) => {
		console.error(e);
		process.exit(1);
	});
